### ISSUE TITLE
Volume is not considered in market logic

### ISSUE THREAD

**Issue by giangd** [Leeps-Lab/flow_market#40]
# Findings
- Older versions do exhibit this behavior
- Jason's version does not have this bug

# Jason's code (correct)
- Contains separate execution functions for cda and flo
- Execution function for cda has three different conditions based for:
- Bid vol vs lowest ask vol (greater than, equal, less than)
- Ask vol vs highest bid vol (greater than, equal, less than) 
- See ```function checkBidCross(chart, bid)``` and ```function checkAskCross(chart, ask)```

# Current code (bug)
- Only contains execution function for flo, and is executing it for cda also

# Possible solutions
- Copy over logic of  ```function checkBidCross(chart, bid)``` and ```	function checkAskCross(chart, ask)``` into ```def update(self):```

# Tests
## Remaining buy test
- Player 1 buy price:8 vol:100
- Player 2 sell price:8 vol:50
- Bug result: all orders execute
- Expected result: player 1's order should remain in the market with vol:50
- [x] Fixed
- [x] Fix market graph

## Remaining sell test
- Player 1 sell price:8 vol:100
- Player 2 buy price:8 vol:50
- Bug result: all orders execute
- Expected result: player 1's order should remain in the market with vol:50
- Current todo: see why cash is not updated but graph is, probably not using an up-to-date version for cash updates
- This bug is also probably related to the bug where the displays do not update sometimes
- [x] Fixed
- [x] Fix market graph

## None remaining test
- Player 1 buy price:8 vol:50
- Player 2 sell price:8 vol:50
- Expected result: no orders remain
- [x] Fixed

## Multiple remaining buy test
- Player 1 buy price:8 vol:50
- Player 2 buy price:8 vol:50
- Player 3 sell price:8 vol:50
- Expected result: one buy order remains with 50
- Bug result: all orders execute
- [x] Fixed

## Multiple remaining sell test
- Player 1 sell price:8 vol:50
- Player 2 sell price:8 vol:50
- Player 3 buy price:8 vol:50
- Expected result: one sell order remains with 50
- Bug result: all orders execute
- [x] Fixed

## Multiple remaining buy test 2
- Player 1 buy price:8 vol:50
- Player 2 buy price:8 vol:50
- Player 3 sell price:8 vol:100
- Expected result: all orders execute
- Bug result: sell order remains with 50
- [x] Fixed
- [x] Fix market graph

## Multiple remaining sell test 2
- Player 1 sell price:8 vol:50
- Player 2 sell price:8 vol:50
- Player 3 buy price:8 vol:100
- Expected result: all orders execute
- Bug result: buy order remains with 50
- [x] Fixed

# Replication steps (CDA)
## Situation 1
- Player 1 buy price:8 vol:100
- Player 2 sell price:8 vol:50
- Bug result: all orders execute
- Expected result: player 1's order should remain in the market with vol:50

## Situation 2
- Player 1 buy price:8 vol:50
- Player 1 buy price:8 vol:50
- Player 2 sell price:8 vol:50
- Bug result: all orders execute
- Expected result: one of player 1's orders should remain in the market

# Todo
- [x] Test if this bug is in older versions
- [x] Write more tests, two player and also multi-player orders
